import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { SolanaWalletProviders } from "@/components/SolanaWalletProviders";

// Inter 폰트 사용 (Geist 대체)
const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff" />
        <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#000000" />
        <meta name="color-scheme" content="light dark" />
        <Script src="/ggwave/ggwave.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${inter.className} antialiased`}
      >
        <SolanaWalletProviders>
          {children}
        </SolanaWalletProviders>
      </body>
    </html>
  );
}
